# Generated by Django 4.1.7 on 2023-04-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PonctualForecast',
            fields=[
                ('calculation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfm.calculation')),
                ('required_agents_number', models.IntegerField()),
                ('agents_number_after_shrinkage', models.IntegerField()),
                ('agents_number_max_occupancy', models.IntegerField()),
                ('service_level', models.IntegerField()),
                ('calls_without_delay', models.IntegerField()),
                ('average_speed', models.IntegerField()),
            ],
            bases=('wfm.calculation',),
        ),
    ]
