# Generated by Django 4.1.7 on 2023-05-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0002_calculation_ponctualforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctualReverseForecast',
            fields=[
                ('calculation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfm.calculation')),
                ('max_calls_number', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('max_calls_with_occupancy', models.IntegerField()),
                ('average_occupancy', models.IntegerField()),
                ('service_level', models.IntegerField()),
            ],
            bases=('wfm.calculation',),
        ),
    ]
