# Generated by Django 4.1.7 on 2023-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0004_multipleperiodtable_multipleperiodforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='type',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
